### ISSUE TITLE
Suggestion: Make argument an object with an exported interface ItfetchParams

### ISSUE THREAD

**Issue by IgorJoergensen** [OmniCar/tfetch#1]
https://github.com/OmniCar/tfetch/blob/d7959efc481838027cfb4e262999056d1496f8fa/src/api.ts#L15

If you don't like anything in this suggestion - then just throw it out and delete issue etc..

Arguments for tfetch could be a single argument - an object instead - would make it easier and cleaner when wanting to use some of the arguments at the end, like nonJsonRequest & validStatusCodes.

Would also open up for an exported Interface for those who (like me) likes to wrap their API calls.

Also propose renaming from tfetch to tFetch - for the sole reason it looks cool 🥇  
Well also because the fetch part will stand out more and t part is more readable since tf have same cross through topside of each character...

So....

```
export interface ItFetchParams {
  url: string,
  method?: httpType,
  body?: object,
  extraHeaders?: IExtraHeader[],
  nonJsonRequest?: boolean,
  validStatusCodes?: number[],
}
```

**Comment by erikoc** [comment]
I would probably name the interface either `ITFetchParams` og just `IFetchParams` but other than that it sounds as a very reasonable change.
It does however make it harder to know what the default values are - e.g. `method = 'GET'`
Maybe we should also name the `nonJsonRequest` --> `jsonRequest` instead as it is more intuitive?
Just open a PR, and let's work on a new release 👍
